name: Latest Blog Articles
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iamrishavraj 1/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-LIST"
          feed_list: "https://dev.to/iamrishavraj1"
